apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app-node
        image: arthurknoep/kube-demo-node-app:latest
        ports:
          - containerPort: 3000
            name: 'http'
        env:
          - name: FILENAME
            value: '/mnt/file.txt'
          - name: DB_HOST
            value: 'db'
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                key: username
                name: db-config
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                key: db-name
                name: db-config
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: app-user-password
                name: db-secret
        resources:
          limits:
            memory: 500Mi
            cpu: 1000m
          requests:
            memory: 100Mi
            cpu: 200m
        volumeMounts:
          - name: file-storage
            mountPath: /mnt
      volumes:
        - name: file-storage
          persistentVolumeClaim:
            claimName: app-pvc
